#!/bin/bash

# Check that we have the right number of parameters, otherwise die. 
if [ "$#" -ne 3 ]; then 
  >&2 echo "Illegal number of parameters (expected 3, got $#). ";
  >&2 echo "Usage: $0 \$SRC \$DIST \$KWARC";
  >&2 echo "Generates html from .html and .xml files"; 
  exit 1;
fi

# read variables
SRC="$1"
DIST="$2"
KWARC="$3"

echo "Generating html from $SRC into $DIST"

# files
BIB_XSL="${SRC}html/bibliography.xsl"


LTOPT="--bibliography=${DIST}ltxml/kcr.bib.xml --format=xhtml --path=${SRC}ltxml --preload=${SRC}ltxml/kwarcbibs.sty.ltxml"

## now we extract all the HTML from kcr.bib
TYPES='article incollection conference workshop book thesis report unpublished misc'
for i in $KWARC; do
    for j in $TYPES; do
    	  xsltproc --stringparam file $i-$j -o ${DIST}tex/$i-$j.tex ${BIB_XSL} ${DIST}ltxml/kwarcpubs.bib.xml;
	      latexmlc ${LTOPT} --destination=${DIST}html/$i-$j.html ${DIST}tex/$i-$j.tex 2> >(tee ${DIST}tex/$i-$j.ltxlog >&2);
    done;
done;

## now we extract all the HTML from kwarccrosrefs.bib
TYPES='wproceedings cproceedings cbook'
for i in $KWARC; do
    for j in $TYPES; do
    	  xsltproc --stringparam file $i-$j -o ${DIST}tex/$i-$j.tex ${BIB_XSL} ${DIST}ltxml/kwarccrossrefs.bib.xml;
	      latexmlc ${LTOPT} --destination=${DIST}html/$i-$j.html ${DIST}tex/$i-$j.tex 2> >(tee ${DIST}tex/$i-$j.ltxlog >&2); 
    done;
done;
