#!/bin/bash

LTOPT='--bibliography=kwarcpubs.bib.xml --bibliography=kwarccrossrefs.bib.xml --bibliography=extcrossrefs.bib.xml --format=xhtml'

KWARC='mkohlhase akohlhase miancu dginev cjucovschi twiesing dmueller frabe cprodescu clange cdavid vzholudev cmueller nmueller fhorozal'

## we make sure that the XML versions of the bibliographies are up to date. 
make xml

## now we extract all the HTML from kwarcpubs.bib
TYPES='article incollection conference workshop book thesis report unpublished misc'
for i in $KWARC; do
    for j in $TYPES; do
    	  xsltproc --stringparam file $i-$j -o $i-$j.tex mybib.xsl kwarcpubs.bib.xml;
	  latexmlc $LTOPT --destination=$i-$j.html --log=$i-$j.ltxlog $i-$j.tex
    done;
done;

## now we extract all the HTML from kwarccrosrefs.bib
TYPES='wproceedings cproceedings cbook'
for i in $KWARC; do
    for j in $TYPES; do
    	  xsltproc --stringparam file $i-$j -o $i-$j.tex mybib.xsl kwarccrossrefs.bib.xml;
	  latexmlc $LTOPT --destination=$i-$j.html --log=$i-$j.ltxlog $i-$j.tex
    done;
done;

for i in $KWARC; do
    echo "generating pubs-$i.html"
    xsltproc --stringparam id $i -o pubs-$i.html publist.xsl publist.xsl
done;    
