#!/bin/bash
KWARC='mkohlhase ako'
TYPES='article incollection inproceedings proceedings thesis report unpublished misc'

for i in $KWARC; do
    for j in $TYPES; do
    	  xsltproc --stringparam file $i-$j -o $i-$j.tex mybib.xsl kwarcpubs.bib.xml;
	  latexmlc --bibliography=kwarcpubs.bib.xml --bibliography=kwarccrossrefs.bib.xml --bibliography=extcrossrefs.bib.xml\
	  	         --format=xhtml --destination=$i-$j.html --log=$i-$j.tex.ltxlog --css=bib.css $i-$j.tex --log=$i-$j.ltxlog\
			 --css=bib.css $i-$j.tex
    done;
done;    

for i in $KWARC; do
    xsltproc --stringparam id $i -o pubs-$i.html publist.xsl publist.xsl
done;    
