#!/bin/bash
KWARC='mkohlhase akohlhase miancu dginev cjucovschi twiesing dmueller frabe cprodescu clange cdavid vzholudev cmueller nmueller fhorozal'
TYPES='article incollection inproceedings proceedings thesis report unpublished misc'

make xml

for i in $KWARC; do
    for j in $TYPES; do
    	  xsltproc --stringparam file $i-$j -o $i-$j.tex mybib.xsl kwarcpubs.bib.xml;
	  latexmlc --bibliography=kwarcpubs.bib.xml --bibliography=kwarccrossrefs.bib.xml --bibliography=extcrossrefs.bib.xml\
	  	   --format=xhtml --destination=$i-$j.html --log=$i-$j.tex.ltxlog --log=$i-$j.ltxlog\
		   $i-$j.tex
    done;
done;    

for i in $KWARC; do
    xsltproc --stringparam id $i -o pubs-$i.html publist.xsl publist.xsl
done;    
