<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:ltx="http://dlmf.nist.gov/LaTeXML">

    <!-- suitable for output generated by LaTeXML -->

    <!-- the entries to search for -->
    <xsl:param name="pubs" select="'mkohlhase'"/>
    <xsl:param name="type" select="'article'"/>

    <xsl:output method="text"/>

    <xsl:template match="/">
      <xsl:text>\documentclass{article}
\usepackage{biblatex}
\usepackage{kwarcbibs}
\bibliography{kwarcpubs,kwarccrossrefs,extcrossrefs}
\let\mypubkeys=\nocite
\begin{document}
      </xsl:text>
      <xsl:for-each select="//ltx:bibentry[contains(ltx:bib-data[@role='pubs'],$pubs) and @type=$type]">
	<xsl:text>\nocite{</xsl:text>
	<xsl:value-of select="./@key"/>
	<xsl:text>}&#xA;</xsl:text>
      </xsl:for-each>
      <xsl:text>\printbibliography&#xA;\end{document}&#xA;</xsl:text>	
    </xsl:template>
</xsl:stylesheet>

