= Files =

The directory contains the bib resources of the KWARC group, most notably the
citation database kwarc.bib.  Note that kwarc.bib is generated by concatenating
the following individual files, and that it is read-only.  Please edit the
following files: 

* preamble.bib – LaTeX preamble that defines shared macros and strings
* kwarcpubs.bib – individual publications of KWARC members (e.g. @article,
  @inproceedings)
* kwarccrossrefs.bib – crossref targets (e.g. @proceedings) edited by KWARC
  members (e.g. when one of us chaired a workshop)
* extpubs.bib – publications by external researchers (which may cross-reference
  targets in kwarccrossrefs.bib!)
* extcrossrefs.bib – crossref targets edited by external researchers,
  regardless of whether KWARC or external publications refer to them.

For making citations in your documents, you can simply continue to use the
all-in-one kwarc.bib (but keep in mind that it is not editable!), or
alternatively you can use the individual files.  In the latter case, use the
following order:
1. preamble.bib
2. *pubs.bib
3. *crossrefs.bib

= Citation styles for URLs =

BibLaTeX is the most reliable way of citing URLs; see the how-to at
http://trac.kwarc.info/KWARC/wiki/BibLaTeX

There are also various unsupported legacy bst (bibTeX style files), most
notably the ones for for hyperrefed citations in alpha.bst. More can be
generated by editing the makefile.

At the moment we have alphahurl.bst 

To make use of these add something like the following to your environment
variables. 

# BibTeX
export BIBINPUTS=".:${HOME}/kwarc/doc/bibs"
export BSTINPUTS=".:${HOME}/tex/lib/bibs"

--EDITING--,
This file does not have any particular order.                    
                                                                 
Do not use any graphical frontend for editing, but use a text    
editor, as the latter makes sure that changes are easy to spot   
when using Subversion's diff.                                    
                                                                
Do not touch anything that you don't understand.                 
                                                                
It is easiest to create new entries by copying and modifying     
existing ones.                                                   

--ONLINE-PUBLICATIONS--,
For online publications, it is strongly recommended to use       
BibLaTeX's @online{foo:on} entries; see                                  
http://trac.kwarc.info/KWARC/wiki/BibLaTeX                      
                                                                
Most online publications come in multiple variants for           
compatibility with legacy publication workflows (such as LNCS).  
The naming scheme is:                                            
                                                                
* @online{entry:on} -- BibLaTeX `online' entry                   
* @webpage{entry:webpage} -- alpha[h]url, an older solution for  
  online citations                                               
* @misc{entry:web} -- plain BibTeX entry                         
* @misc{entry:base} -- crossref'd by the others above, contains  
  common fields, not suitable for citation                       

--PUBLICATION-LIST-GENERATION--,
The publication lists on the KWARC homepage are generated from   
this file; see                                                   
http://trac.kwarc.info/wsml/wiki/PublicationLists               

