###########################################################################
# Automating LaTeX-proposal management by make.
# The participants work on proposal.tex in "draft" mode, which gives a lot
# of information to the developers. Variants submit.tex and public.tex are
# used to prepare official versions (hiding development/private info). 
###########################################################################
# possibly customize the following variables to your setting
REPORT = finalreport.tex# 	# the report
PROP.dir = ../../..#            # The LaTeX-proposal class directory
BIB = ../lib/dummy.bib# # bibTeX databases
###########################################################################
include $(PROP.dir)/lib/Makefile.dfgproposal 
